# Generated by Django 3.0.5 on 2020-04-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.TextField()),
                ('book_title', models.TextField()),
                ('book_author', models.TextField()),
                ('year_of_publication', models.IntegerField()),
                ('publisher', models.TextField()),
                ('image_url_s', models.TextField()),
                ('image_url_m', models.TextField()),
                ('image_url_l', models.TextField()),
            ],
        ),
    ]
